# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 13:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearnview_core', '0002_auto_20170706_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
