# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearnview_core', '0005_module_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpagehistory',
            name='last_visited_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
