# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 07:09
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearnview_core', '0007_auto_20170726_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
