# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearnview_core', '0008_course_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='opened',
        ),
        migrations.AlterField(
            model_name='studentpagehistory',
            name='last_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_page', to='mylearnview_core.Page', verbose_name='Last page'),
        ),
        migrations.AlterField(
            model_name='studentpagehistory',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mylearnview_core.Module'),
        ),
    ]
