# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearnview_core', '0010_studentcourseaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpagenote',
            name='coord_x',
            field=models.IntegerField(blank=True, default=0, verbose_name='Coordinate X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpagenote',
            name='coord_y',
            field=models.IntegerField(blank=True, default=0, verbose_name='Coordinate Y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mylearnview_core.Module'),
        ),
        migrations.AlterField(
            model_name='studentcourseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_acesses', to='mylearnview_core.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studentpagenote',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mylearnview_core.Page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='studentpagenote',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
