# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearnview_core', '0011_auto_20180302_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpagenote',
            name='coord_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coordinate X'),
        ),
        migrations.AlterField(
            model_name='studentpagenote',
            name='coord_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coordinate Y'),
        ),
    ]
