# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_studentpagehistory_last_visited_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='sort_index',
            field=models.PositiveSmallIntegerField(verbose_name='Sort index'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sort_index',
            field=models.PositiveSmallIntegerField(verbose_name='Sort index'),
        ),
    ]
