# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0012_auto_20180302_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpagenote',
            name='coord_x',
        ),
        migrations.RemoveField(
            model_name='studentpagenote',
            name='coord_y',
        ),
        migrations.AddField(
            model_name='studentpagenote',
            name='coord',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coordinate'),
        ),
    ]
