# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 14:17
from __future__ import unicode_literals

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0013_auto_20180305_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('-course__id', 'sort_index')},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('-module__id', 'sort_index')},
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app_core.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sort_index',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sort index'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_file_reference',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=256, verbose_name='Reference to image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sort_index',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sort index'),
        ),
        migrations.AlterField(
            model_name='studentpagenote',
            name='coord',
            field=models.FloatField(blank=True, null=True, verbose_name='Coordinate'),
        ),
    ]
