# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0014_auto_20180331_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpagenote',
            options={'ordering': ('-created_datetime',)},
        ),
        migrations.AlterField(
            model_name='module',
            name='pages_ready',
            field=models.BooleanField(default=True, verbose_name='Page status'),
        ),
    ]
